kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: postgres
  labels:
    component: postgres
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"