{{/*
Copyright 2018 goglides and it's authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.apiserver }}

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      volumes:
      - name: data-store
        emptyDir: {}
      containers:
      - name: api-server
        image: {{ .Values.images.tags.open_event_apiserver }}
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        livenessProbe:
          httpGet:
            path: /health-check/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: api-server
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: PYTHONUNBUFFERED
          value: 'TRUE'
        - name: DEPLOYMENT
          value: 'api'
        - name: FORCE_SSL
          value: 'yes'
        volumeMounts:
        - mountPath: /opev/open_event/static/uploads/
          name: data-store
      - name: celery
        image: {{ .Values.images.tags.open_event_apiserver }}
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        envFrom:
        - configMapRef:
            name: api-server
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: DEPLOYMENT
          value: 'celery'
        volumeMounts:
        - mountPath: /opev/open_event/static/uploads/
          name: data-store
      restartPolicy: Always
{{- end }}