kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    component: elasticsearch
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"