#
# Deployment of the API Server
#
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api-server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      volumes:
      - name: data-store
        emptyDir: {}
      containers:
      - name: api-server
        image: bkpandey/open-event-server:development
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: api-server
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: PYTHONUNBUFFERED
          value: 'TRUE'
        - name: DEPLOYMENT
          value: 'api'
        - name: FORCE_SSL
          value: 'yes'
        volumeMounts:
        - mountPath: /opev/open_event/static/uploads/
          name: data-store
      restartPolicy: Always
